#      ____                                            ____  ____  ____
#     / __ \_________ __________  ____  __  ___  __   / __ \/ __ \/ __ \
#    / / / / ___/ __ `/ ___/ __ \/ __ \/ / / / |/_/  / /_/ / /_/ / / / /
#   / /_/ / /  / /_/ / /__/ /_/ / / / / /_/ />  <   / ____/ _, _/ /_/ /
#  /_____/_/   \__,_/\___/\____/_/ /_/\__, /_/|_|  /_/   /_/ |_|\____/
#                                    /____/
# By MyNameIsKiyoshi Version (1.20.5) Block CMDs, TabComplete, F3-Mark and More!! (1.19.2)
# GitHub: https://github.com/MyNameIsKiyoshi Discord: https://discord.gg/ka7uGKfy7p (Pro Version)

# Don't Touch This Section
vConfig: "20"

# F3-Mark (Hex Support https://g.co/kgs/56o9TW)
F3Mark:
  Status: true
  Mark: "&9&lProtected By DraconyX PRO"

PluginsSpoof: # Message Editable In language\language.yml
  # You can find ohter languages in
  Status: false

# TabComplete Blocked Commands
# If are u using FastAsyncWorldEdit(Fawe) // WorldEdit
# Use this syntax (https://i.imgur.com/y26seR7.png)
bTabCommands:
  - "version"
  - "about"
  - "version"
  - "ver"
  - "?"
  - "bukkit"

# Blocked Commands
bCommands:
  - "/version"
  - "/about"
  - "/version"
  - "/ver"
  - "/?"
  - "/bukkit"

# Sounds System Link Of All Sounds Below.
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
Sounds:
  Status: true
  AccessDenied: "ENTITY_VILLAGER_NO"
