name: DraconyxPro
version: '1.19.3'
main: fur.kiysohi.draconyxpro.Main
api-version: 1.19
authors: [ MyNameIsKiyoshi ]
description: Block CMDs, TabComplete, F3-Mark and More!!
website: https://github.kiyoshi.space
softdepend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  draconyx:
    description: "DraconyX PRO Super Anti Blocker."
    aliases: [ dx ]
